# Generated by Django 3.2.1 on 2024-02-29 03:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240229_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='trans_plan', unique=True),
        ),
    ]
