# Generated by Django 3.2.1 on 2024-03-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_withdrawal_w_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wfpt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
