# Generated by Django 3.2.1 on 2024-02-27 03:01

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('profit', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=200)),
                ('bonus', models.CharField(max_length=200)),
                ('min', models.CharField(max_length=200)),
                ('max', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('reviewing', models.BooleanField(default=True)),
                ('confirm', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_msg', models.CharField(blank=True, default='Your payment have been confirmed, your investment is active.', max_length=255, null=True)),
                ('reviewing_msg', models.CharField(blank=True, default='Just a minute, we are reviewing your selected plan and payment.', max_length=255, null=True)),
                ('confirm_msg', models.CharField(blank=True, default='Your investment request was rejected, please contact support help.', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
