# Generated by Django 3.2.1 on 2024-02-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='confirm',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='package',
            name='confirm_msg',
        ),
        migrations.RemoveField(
            model_name='package',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='package',
            name='rejected_msg',
        ),
        migrations.RemoveField(
            model_name='package',
            name='reviewing',
        ),
        migrations.RemoveField(
            model_name='package',
            name='reviewing_msg',
        ),
    ]
