# Generated by Django 3.2.1 on 2024-03-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_userpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='recent',
            field=models.DateField(),
        ),
    ]
