# Generated by Django 3.2.1 on 2024-02-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_auto_20240227_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recent',
            field=models.DateField(auto_now=True),
        ),
    ]
