# Generated by Django 3.2.1 on 2024-03-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_alter_userpackage_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='recent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
