# Generated by Django 3.2.1 on 2024-02-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_package_recent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-recent', '-post_date']},
        ),
    ]
