# Generated by Django 3.2.1 on 2024-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_alter_userpackage_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='wdrw_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
