# Generated by Django 3.2.1 on 2024-02-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_message_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ContactUsMessage',
        ),
    ]
